name: compile_deploy_latex
on: [push]
jobs:
  upload-doc-johannes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'johannes'
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: forallxbris.tex
      - name: Rename PDF file
        run: mv ./forallxbris.pdf ./forallxbris-js.pdf
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v2
        with:
          name: forallxbris-js.pdf
          path: ./
  deploy:
    needs: [upload-doc-johannes]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: gh-pages
