name: compile_deploy_latex
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          ref: 'johannes' 
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: forallxbris.tex
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: forallxbris.pdf
          path: ./github_artifacts
  deploy:
    needs: [build_latex]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          path: github_artifacts
      - name: Debug - List contents of github_artifacts
        run: ls -R github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: gh-pages
